### ISSUE TITLE
Seite 9 & 39 werden nicht generiert 

### ISSUE THREAD

**Issue by derNiklaas** [Jugendhackt/Besteuerung#1]
Hi. 
Ich wollte mir mal euer Projekt anschauen, jedoch wurden die Seiten 9 und 39 nicht generiert.

Mit freundlichen Grüßen,
Niklas

**Comment by NguyHoangTrung** [comment]
Hallo Niklas!

Eigentlich waren die Probleme auf den Dateien meines Latops gefixt, nur wurden die letzten Änderungen wohl nicht übernommen. :/ 
Danke für das Engagement! Jetzt ist alles so, wie es sein sollte!

MfG Trung

P.S. Den Restart nach Spielende hab ich jetzt entfernt, ist aber hoffentlich kein Problem.

**Comment by derNiklaas** [comment]
Hi. 
Ich schließe dann mal die Pull Request und dieses Issue. 

Noch einen schönen Tag. 

Mit freundlichen Grüßen,
Niklas

**Comment by derNiklaas** [comment]
#closed
